//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroConsola
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProducto
    {
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioP { get; set; }
    }
}
