//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajeroConsola
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProducto
    {
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioP { get; set; }
    }
}
